### ISSUE TITLE
Urlaub und Krank-Tage sollen vom MA zurückgezogen werden können (Prio 2)

### ISSUE THREAD

**Issue by albig** [verdigado/odoo-customize#10]
## Mit Genehmigungs-Workflow

* so lange ein Urlaub noch nicht genehmigt ist, solle er vom MA bearbeitet oder zurückgezogen werden können. Das funktioniert bereits.
* ein genehmigter Urlaub in der Zukunft soll durch den MA oder seinem "Genehmiger" (Employee's Approver) bearbeitet oder zurückgezogen werden können. Aktuell kann der Genehmiger nur genehmigen. Nicht ablehnen, bearbeiten oder löschen.

## Ohne Genehmigungs-Workflow

* Urlaub in der Zukunft sollen vom MA bearbeitet und zurückgezogen werden können.

#### als Mitarbeiter 
* Eigener Urlaub kann nicht selbst "abgelehnt" werden.
* "Bearbeiten" ist zwar möglich, aber keins der Felder (Start, Stop, Zeitraum) lässt sich ändern.
![2023-09-14_13-42](https://github.com/verdigado/odoo-customize/assets/3354500/0a014d8a-197c-4bf5-b082-e688e65cac1f)

#### mit Rechten "Time Off Officer"

* ein Ablehnen ist möglich
* Ändern / Bearbeiten ist nicht möglich. Nur das Feld "Beschreibung" kann bearbeitet werden. Nicht Start, Stop, Dauer.
* keine erneute Genehmigung möglich
* die Rechte "Time Off Officer" scheinen hier völlig nutzlos zu sein

#### mit Rechten "Administrator"

* Ablehnen ist möglich
* "Mark as Draft" möglich
* Bearbeiten ist möglich
* erneutes Genehmigen ist möglich
* Löschen des Antrags ist möglich

#### als Mitarbeiter
* Ablehnen
* Bearbeiten
* Löschen

von zukünftigen Anträgen

* Ablehnen
* Bearbeiten

von vergangenen Anträgen 

sollte möglich sein.

#### als "Time Off Officer"

zusätzlich: löschen von vergangenen Anträgen.

**Comment by HueHa-v** [comment]
**Zur Diskussion:**
Wenn ein MA krank ist, sollten Krankheitstage auch Urlaubstage "überlagern" können. Aktuell kann ein Krankheitstag nicht über einen Urlaub gebucht werden. Es müsste erst der Urlaub storniert, dann der Urlaub bis zum Krankheitstag neu eingetragen, die Krankheitstage hinterlegt und bei Bedarf dann wieder Urlaub gebucht werden.

Einfacher wäre es, wenn die Krankheitstage einen Urlaub oder andere Abwesenheiten überlagern und die Berechnung neu anstoßen - Urlaubstage in Anzahl der Krankheitstage wieder gut schreiben etc.

**Comment by hbrunn** [comment]
Das Bearbeiten von genehmigtem Urlaub (egal ob der Urlaubstyp genehmigungspflichtig ist oder nicht) stellt sich als ziemlich komplex heraus, deshalb hier ein anderer Vorschlag:

Ich habe den 'Reset to draft'-Button fur zukünftige Urlaube in allen Zuständen erlaubt. Wenn ein Urlaub genehmigt werden muss, sollten doch ohnehin Änderungen daran eine neue Genehmigung erfordern? Und für nicht genehmigungspflichtige Urlaube nehmen wir dann einfach denselben Flow, dh in allen Fällen wenn etwas bearbeitet werden soll: Reset to draft, bearbeiten, bestätigen. Ist das akzeptabel?

Das für Employees, Officer/Manager können ja ohnehin schon bearbeiten/ablehnen unter Abwesenheiten/Genehmigungen/Abwesenheiten und da den 'Zu genehmigen'-Filter wegnehmen. Da das ziemlich umständlich ist habe ich für Abwesenheitsverantwortlicher/in (da musste ich schmunzeln) ein Menuitem 'All leaves' zugefügt, das zeigt einfach eine Liste von allen Abwesenheiten die per ir.rules zugänglich sind und erlaubt Managern dann auch Resets und dadurch Löschen.

Was Krankheit im Urlaub angeht, habe ich angefangen mit einem Flag 'Überlappungen erlauben' auf Urlaubstypen, das funktioniert schon. Dass diese Zeit dann wieder vom Urlaub abgezogen wird ist etwas tricky, das kommt dann nächste Woche.
