### ISSUE TITLE
Erhalt der "Adjustments" bei der Neuberechnung von Überstunden (Prio 2)

### ISSUE THREAD

**Issue by albig** [verdigado/odoo-customize#16]
Vom laufende Gleitzeitkonto soll durch einen Personalverantwortlichen Stunden in Ausgleichstage umgewandelt werden können. Das ist grundsätzlich mit Odoo15-Community bereits jetzt möglich.

Es muss sichergestellt werden, dass die Stunden korrekt vom Gleitzeitkonto abgezogen werden und auch bei Neuberechnungen des Gleitzeitkontostands berücksichtigt werden.

**Comment by albig** [comment]
noch mal prüfen und näher spezifizieren.

**Comment by albig** [comment]
Thema ist hier: Erhalt der "Adjustments" bei der Neuberechnung von Überstunden.

**Comment by hbrunn** [comment]
note to self: domain in https://github.com/OCA/OCB/blob/15.0/addons/hr_attendance/models/res_company.py#L25 anpassen

**Comment by albig** [comment]
Schaltet man die Option "Überstunden" über Einstellungen -> Anwesenheiten aus oder verändert den Start-Zeitpunkt, wird die Tabelle `hr_attendance_overtime` bis zum neuen Start-Zeitpunkt geleert.

Schaltet man die Option wieder ein, werden die Overtimes neu berechnet.

Aber die Adjustements fehlen dann. Diese können kommen aus

- Manuellen Anpassungen durch `hr_attendance_overtime_manual`
- Abwesenheiten mit Typ Überstunden oder Krankheiten

Den letzteren Fall kann man sicherlich wieder herstellen. Bei den manuellen Anpassungen bin ich mir nicht sicher.
