### ISSUE TITLE
Standardbenutzerrechte?

### ISSUE THREAD

**Issue by hbrunn** [verdigado/odoo-customize#20]
um Probleme wie gerade besprochen zu verhindern, will ich gerne in die Demodaten von verdigado_attendance ein paar Benutzer stecken die möglichst genau die Rechte haben die verschiedene Arten Benutzer auf echten Installationen wiederspiegeln. Das wird auch für komplexere CI-Tests relevant.

Wie geht Ihr momentan damit um? Stellt ein Admin von Hand die Gruppen pro Benutzer ein? Das scheint mir schlecht zu skalieren, wie wäre auf der User-Form ein eigener Header 'Verdigado' wo dann eine Gruppe/Rolle wie 'Benutzer', 'Manager' oder was Ihr sonst noch an Abstufungen habt ausgewählt werden kann? Das ist eine kleine Mühe und hat auch den Vorteil dass dann ziemlich einfach per Update alle Benutzer einer Gruppe Rechte dazu bekommen/weggenommen werden können.

Alternativ gibt es auch https://github.com/OCA/server-backend/tree/15.0/base_user_role das dieses Konzept noch etwas weiter treibt.

Ich denke irgendetwas in der Art braucht Ihr schon wenn das großflächig ausgerollt wird. Oder kommen am Ende die Gruppen ohnehin von ldap/oidc? (da müsste ich dann die entsprechenden Module irgendwann noch migrieren)

**Comment by albig** [comment]
Bei den aktuellen Setups ist es in der Tat so, dass ein Admin die Rechte setzt.

Ein Setup ist ans LDAP angebunden. Neue Nutzer werden dann automatisch von einer Benutzervorlage angelegt. Das Feature kommt mit `auth_ldap`. Gruppen werden darüber nicht ausgetauscht. Das wäre aber bei manchen Szenarien denkbar.

Wenn man Nutzer-Rechte ändern will, muss man das dann in jeden einzelnen Nutzer manuel tun. Toll ist das nicht.

Also ja, wir können hier eine Lösung gebrauchen. Wenn Du sagst, es ist mit "wenig Mühe" im User-Form machbar, dann würde ich sagen, machen wir das.

**Comment by hbrunn** [comment]
prima, ich lege dann die entsprechende Struktur and und Du fügst die xmlids der Gruppen im Code zu die dazu gehören? Bloss BenutzerIn/Admin oder gibt es noch mehr Rollen?

Sobald es um mehr als eine Handvoll Benutzer geht, und aus ldap ohnehin ableitbar ist welche Benutzer welche Rolle haben, rate ich doch sehr zu https://github.com/OCA/server-auth/tree/15.0/users_ldap_groups - damit muss dann im besten Fall gar nichts auf der Odoo-Seite angepasst werden was Benutzerrechte angeht.

Und die verdigado-spezifischen Gruppen sind dann trotzdem nützlich, weil dann bloss ein Mapping (ldap query) -> (verdigado-gruppe) nötig ist, und nicht etliche Mappings fur die verschiedenen Odoo-Gruppen. Und das erlaubt dann auch weiterhin die Anpassung von Rechter per Code-Update, indem bei den verdigado-Gruppen implied_ids zugefügt oder weggenommen werden.

Noch allgemein als Krücke zum bulk update von Rechten: Ist https://github.com/OCA/server-ux/tree/15.0/mass_editing bekannt?

**Comment by georgloesel** [comment]
im Rahmen des JF am 11.9. kurz angesprochen: 
- wenn die Kunde:innen das Produkt als Teil der Teamtools buchen, gibt es in jedem Fall einen UCS als Identitätsprovider, der dann für das Setzen der Benutzerrechte genutzt werden kann.
