### ISSUE TITLE
Organigram empty for Admin role

### ISSUE THREAD

**Issue by albig** [verdigado/odoo-customize#22]
With the change in #19, a user with admin role always sees and empty organigram in employees.

## Before:
![2023-09-22_16-52](https://github.com/verdigado/odoo-customize/assets/3354500/66e44351-f0e6-4fe0-a178-9a5a9ea7d060)

## Now:
![2023-09-22_16-59](https://github.com/verdigado/odoo-customize/assets/3354500/51cedf44-f9ab-4b16-9fb5-e95b18a820f3)

For users with role "HR Manager / Attendance Officer", the organigram is present.

**Comment by hbrunn** [comment]
hier brauchen wir kein Englisch, oder?

Das liegt an der Regel die public employees auf das eigene Department beschränkt (und sollte eigentlich unabhängig von der Gruppe sein - sind zufällig bei den Attendance Officers die Mitarbeiter im selben Department?)

Soll ich die Regel ändern so dass für die public employees immer auch die Untergebenen und Vorgesetzten sichtbar sind? Alternative wäre in dem Controller der die Daten für das Organigramm erzeugt die Zugriffsrechte zu umgehen, dann gibt es aber Fehler wenn im Organigramm auf eins der Records geklickt wird.

**Comment by albig** [comment]
Nein Englisch brauchen wir hier nicht unbedingt.

Mir geht es hier um die Nutzer-Administrations-Rolle. Also Nutzer, die u.U. gar kein Employee sind. Und wenn, gehören sie nicht unbedingt einem Departement an.

Mit folgenden Rechten ...

![2023-09-25_10-04](https://github.com/verdigado/odoo-customize/assets/3354500/9a5ef4a2-285e-46c8-9a4a-73a4bb271771)

... sind ja alle Employees sichtbar und bearbeitbar.

Das Organigram funktioniert aber nur, wenn der Nutzer auch Mitarbeiter ist und auch nur für sein Department.

Wünschenswert wäre aber, dass ein Nutzer mit Administrations-Rolle das korrekte Organigram aller Mitarbeiter sehen kann. 

Hilft da schon dein Ansatz, die Regel zu ändern?

**Comment by hbrunn** [comment]
noch nicht ganz, ich würde dann für die Admins eine extra-Regel hinzufügen die die Beschränkungen auf hr.employee.public wieder aufhebt, so wie bei den anderen Modellen?

**Comment by albig** [comment]
Klingt richtig. 

So, oder?

* Employee -> `Administrator`: soll alle Employees sehen und bearbeiten bearbeiten inkl. Organigram
* Employee -> `Officer`: soll SEINE Empoyees sehen und bearbeiten inkl. Organigram
