### ISSUE TITLE
Attendance report does not show and compute adjusted overtimes

### ISSUE THREAD

**Issue by albig** [verdigado/odoo-customize#23]
There is a difference in the total amount of overtimes, if adjusted overtimes are present. Like generated with `hr_attendance_manual`.

These entries have `hr_attendance_overtime.adjustment = True` . The result in the total sum of overtime is correct. If you look at the attendance report, these times are not shown and not taken into account.

## Example

Overtime is 16:16h:

![2023-09-22_17-08](https://github.com/verdigado/odoo-customize/assets/3354500/e3d380e0-d003-4624-81ce-12e3df492b0c)

Attendance Report over full time is 40:13h

![2023-09-22_17-21](https://github.com/verdigado/odoo-customize/assets/3354500/b39ae571-55c1-4ac9-b54d-b5d8e3799388)

The adjusted overtimes are mostly in april.

**Comment by hbrunn** [comment]
die adjustments müssen dann mit invertiertem Vorzeichen dazu gerechnet werden, richtig?

**Comment by albig** [comment]
Genau. So würde ich das erwarten. Im konkreten Fall müsste in der Spalte "Überstunden" die Adjustements negativ erscheinen - wie am 11.4.2023, der aber ein "Fehltag" ist.

![2023-09-25_10-16](https://github.com/verdigado/odoo-customize/assets/3354500/b6bad6c3-483b-4f2b-b49d-93075e0379c3)
