### ISSUE TITLE
Das Saldo des Arbeitsstundenkontos soll prominent angezeigt werden

### ISSUE THREAD

**Issue by albig** [verdigado/odoo-customize#3]
Aktuell können im Menü "Abwesenheiten" die Überstunden angezeigt werden. Die Anzeige ist aber fehlerhaft (siehe weitere Tickets).
Alternativ kann mit dem Modul "Theoretische vs. Tatsächliche Anwesenheit" ([hr_attendance_report_theoretical_time](https://github.com/OCA/hr-attendance/tree/15.0/hr_attendance_report_theoretical_time)) ein Bericht über die Anwesenheiten erstellt werden, der eine korrekte (Über-) Stundenzahl ausgibt. Dieser Weg ist allerdings für die Nutzenden relativ aufwändig.

**Comment by hbrunn** [comment]
ist der Smartbutton oben rechts auf den Mitarbeiter-Records bekannt? Der zeigt momentan noch die verkehrte Zahl an, aber das wird ja in #2 adressiert.

Wie wäre ein Widget oben rechts im Menübalken? Weiße 0 (oder nichts) wenn es keine Überstunden gibt, rot mit negativem Vorzeichen wenn zuwenig Zeit geschrieben wurde, grün ohne Vorzeichen für Überstunden? Und ein Click darauf leitet zur Anwesenheitsliste (oder dem noch nicht existierenden Überstunden-zu-Urlaub-Formular)?

**Comment by albig** [comment]
Der Button ist bekannt. Die Widget-Idee finde ich grundsätzlich gut. Ich würde natürlich gerne die anderen Stellen vereinheitlichen / fixen bzw. darauf aufbauen:

Die - ich nennen sie - "Odoo"-Überstunden werden an folgenden Stellen angezeigt (ggf. noch mehr):

## 1. Personal -> Employee (nur für den Personalverantwortlichen)

![Odoo - employee_42](https://github.com/verdigado/odoo-customize/assets/3354500/5fe8a1ae-4ade-4c3a-8b7d-86a16ade4660)

Das führt dann zur Liste der Überstunden - aber nicht zur Liste der gebuchten Antwesenheiten:

![Odoo - Überstunden](https://github.com/verdigado/odoo-customize/assets/3354500/120b10ff-f2a6-4171-8515-069bbfe30389)

Im Beispiel fehlt z.B. eine "Überstunde" für den Do, 22.06.2023, was ein Arbeitstag sein müsste.

## 2. Anwesenheiten -> Berichtswesen -> Anwesenheitsanalyse (nur für den Personalverantwortlichen)

Für den Personalverantwortlichen ist der Bericht unter Anwesenheiten sehr nützlich - wenn auch Odoo-spezifisch speziell. Den richtigen Überstunden-Wert bekommt man wie unter "Personal", indem man alle Zeiten berücksichtigt. Dass das praktikabel ist, wenn das Tool mehrere Jahre im Einsatz ist, bezweifle ich. Es wird vermutlich nur der relative Wert der letzten Monate auswertbar sein.

![Odoo - Anwesenheitsanalyse (1)](https://github.com/verdigado/odoo-customize/assets/3354500/83744715-0cd3-4ab7-8840-31638e96247e)

Den Bericht kann _nicht_ der Mitarbeitende und auch nicht der direkte Vorgesetzte sehen. Nur der "Personalverantwortliche", der immer - soweit mein Verständnis - alle Mitarbeiter eines Unternehmens sehen und bearbeiten kann.

## 3. Abwesenheiten -> Kalender (nur für den Mitarbeitenden)

Beispiel employee_42 == user_24 (login) == partner_59

Der Mitarbeitende kann hier "prominent" seine Überstunden im Kalender sehen.

Nachteile

* die Zahl wird dezimal ausgegeben, was unbrauchbar ist. Im konkreten Fall: 42,59 == 42:35h. Das ist natürlich mathematisch korrekt.
* es gibt keinen Link zu den erfassten Zeiten im Anwesenheitsmodul
* ist die Zahl negativ, wird das Widget nicht angezeigt. Das hat z.B. die Firma Mint System GmbH im Modul [hr_attendance_overtime_negative_hours](https://github.com/Mint-System/Odoo-Apps-HR/tree/15.0/hr_attendance_overtime_negative_hours) gefixt. In dem Repo sind ggf. noch weitere, interessante HR-Attendance-Module.

![Odoo - Dashboard  2023  (4)](https://github.com/verdigado/odoo-customize/assets/3354500/7ff3a8d5-94bb-4eea-8eb4-8244195cb384)

**Comment by tv-openbig** [comment]
Ich habe hier nochmal ein Dokument verlinkt, mit  dem thematischen Schwerpunkt Management von Überstunden und auch Anpassung der Berechnung von Überstunden und Anzeige Optimierung (insbesondere Pausenzeit) nahe am Odoo Standard. Wir waren uns im Meeting ja einig, dass wir das hr_attendance_overtime Modul möglichst umschiffen, da Teile inzwischen in v15 enthalten sind (z.B. Zuweisung von Überstunden zu einem Konto) und somit zumindestens ein Teil obsolet ist und auch der Prozess der finalen Zuweisung von Überstunden nicht so einfach ist, vielleicht aber mehr Kontrolle bieten würde. Insofern sehe ich meinen alternativen Vorschlag auch erstmal als Diskussionsgrundlage an. 


https://docs.google.com/document/d/1feip038O80FQw01FBsX1lfETvj455UJX/edit

**Comment by tv-openbig** [comment]
Neuer Dokumentenpafd: https://cloud.verdigado.com/index.php/s/FNqxN2oLyZo6sFH

**Comment by tv-openbig** [comment]
@hbrunn @albig Es wird vereinbart, dass neben den Activities noch ein Icon in der Menüleiste angezeigt, die die aktuellen Überstunden anzeigt. Diskutiert wird noch "Refresh" oder nicht, soll aber nicht angezeigt werden.

**Comment by hbrunn** [comment]
in https://github.com/verdigado/odoo-customize/pull/21 zeige ich jetzt einfach die Nummer aus dem hr_holidays_attendance.holiday_status_extra_hours Urlaubstypen an. Oder soll das die Summe von hr_holidays_attendance.holiday_status_extra_hours und hr_holidays.holiday_status_comp sein?

**Comment by hbrunn** [comment]
soeben den link angepasst, den Rest lassen wir wie besprochen so wie er ist

**Comment by albig** [comment]
fixed mit #21
