### ISSUE TITLE
Check-out für Mitarbeiter nicht mehr möglich

### ISSUE THREAD

**Issue by albig** [verdigado/odoo-customize#30]
Nach den letzten Änderungen aus #18 und dem zugehörigen Modul `hr_attendance_break` können Mitarbeitende mit den Rechten "Manuelle Anwesenheit" sich nicht mehr abmelden.

![2023-09-29_15-34](https://github.com/verdigado/odoo-customize/assets/3354500/95584339-35d6-4425-95c2-aced2fa40bdf)

Provisorisch habe ich jetzt auf den live genutzten Instanzen beim Modell `hr.attendance.overtime` die Rechte für `hr.attendance.overtime.system.user` den Schreibzugriff erteilt.

@hbrunn weiß sicher, wie das verursacht wird und wo man es richtig behebt.

**Comment by hbrunn** [comment]
@albig sollte mit dem letzten patch auf hr_attendance_break behoben sein - code muss hier writes sudo()'en, und den Schreibzugriff kannst Du besser wieder wegnehmen

**Comment by albig** [comment]
Das funktioniert, vielen Dank. Der provisorische Zugriffsschutz ist wieder entfernt.
