### ISSUE TITLE
Labels beim Pause beenden (Prio 3)

### ISSUE THREAD

**Issue by albig** [verdigado/odoo-customize#35]
Möchte man die Pause beenden, steht dort

"Anklicken Abmelden or to return from break"

Der Test "Anklicken Abmelden" macht hier keinen Sinn und soll entfallen.

![2023-10-02_12-13](https://github.com/verdigado/odoo-customize/assets/3354500/4744f182-e33b-4b4e-9e12-05720f2c02ea)

**Comment by hbrunn** [comment]
ist das ein Fluke auf der Testdatenbank? (kein Übersetzungen überschreiben gewählt?)

Auf einer frischen Datenbank sieht das so aus:

![image](https://github.com/verdigado/odoo-customize/assets/2563186/38ec5056-c14b-4b82-b091-9e0eb16a7dbf)

was konsistent ist mit der (mM etwas unglücklichen) Übersetzung von

![image](https://github.com/verdigado/odoo-customize/assets/2563186/3bf68233-71dd-4a21-9136-fc6b110a43a5)

Ich wurde da ja jeweils ein "zum" einfügen.

**Comment by albig** [comment]
Das war nicht mein Punkt. Die Labels waren in meinem Screenshot noch nicht übersetzt.

Ist man in der Pause, macht der Text "Anklicken Abmelden" keinen Sinn, weil es den Button nicht gibt:

![2023-10-23_11-37](https://github.com/verdigado/odoo-customize/assets/3354500/227774a4-8681-42a5-ad02-70e0a17cd2a7)

Ein "zum" wäre eine Idee. oder das "Anklicken" entfernen.

**Comment by albig** [comment]
Kannst Du das bitte noch übernehmen (oder besser machen) @hbrunn ? https://github.com/verdigado/hr-attendance/commit/7247c8c2a718d3234a4b9f3fcfca82a987b41826

**Comment by hbrunn** [comment]
das ist jetzt in oca/hr-attendance@0fb201b4804 repariert

**Comment by albig** [comment]
Fixed in https://github.com/OCA/hr-attendance/commit/0fb201b4804
