### ISSUE TITLE
Doppelten und fehlerhaften Feiertags-Wizard entfernen (Prio 2)

### ISSUE THREAD

**Issue by albig** [verdigado/odoo-customize#40]
Es gibt zwei Feiertags-Wizards:

1. `hr_holidays_public`: `holidays_public_next_year_wizard_view`
2.  `l10n_de_holidays`: `hr_holidays_public_generator_view`

![2023-10-23_11-43](https://github.com/verdigado/odoo-customize/assets/3354500/8bc8c399-9bf7-461b-b1a8-2b6178ae8aba)

Nr. 1 funktioniert nicht korrekt, sondern kopiert einfach die Feiertage von einem Jahr auf das nächste, ohne die variablen Feiertage ("Ostern") zu berücksichtigen.

Dieser Wizard müsste ausgeblendet werden.

**Comment by hbrunn** [comment]
wollen wir hier die grosse Lösung (=den Wizard von hr_holidays_public ertüchtigen dass er auch für DE funktioniert, das dauert einige Stunden) oder die schnelle, in der einfach das Menü versteckt wird?

**Comment by albig** [comment]
Nur die kleine Lösung bitte.
