### ISSUE TITLE
Anpassung der Mailtexte / Notifications auf deutsch bzw. auf "GRÜN"

### ISSUE THREAD

**Issue by georgloesel** [verdigado/odoo-customize#59]
Die Hinweistexte für anstehende Überprüfungen oder Informationen sind noch auf englisch. 
Übersetzung ist hier notwendig. 
Der Ort der Original texte ist zum Teil noch unklar
- eine Quelle ist (im Entwicklermodus): 
- 1. Einstellungen / Technisch /  Email / Email-Vorlagen
- 2. Serveraktionen
nach Abschluss des issues sollten die text auch bei der Anlage von templates berücksichtigt werden (siehe -> #58 )

**Comment by albig** [comment]
`po`-Datei erzeugen (Einstellungen -> Übersetzungen) und in `verdigado_attendance` einbauen.

**Comment by albig** [comment]
Wir definieren die Daten und übernehmen das als XML-Daten in `verdigado_attendance`.
