### ISSUE TITLE
Soll-Arbeitszeit Anwesenheitsbericht fehlerhaft, wenn ist == soll

### ISSUE THREAD

**Issue by albig** [verdigado/odoo-customize#65]
Im Bericht "Anwesenheiten" -> "Berichtswesen" stimmt die Spalte "Soll-Zeit" nicht, wenn genau die Soll-Arbeitszeit eingetragen wurde.

Beispiel:

MA arbeitet regulär 6:24h pro Tag. Er bucht am 21. und 22.11.2023 jeweils genau 6:24h.

- am 21.11.2023 ist regulärer Arbeitstag. Hier erscheint als Soll-Arbeitszeit "0:00" (falsch). Auf das Gleitzeitkonto gehen "0:00" (das ist korrekt) (1+2)
- am 22.11.2023 ist Feiertag, die Soll-Arbeitszeit wird (korrekt) mit "0:00" angezeigt. Auf das Gleitzeitkonto gehen "6:24". (3+4)
- bucht der MA nur 6:23h, dann steht am regulären Arbeitstag eine Soll-Arbeitszeit von "6:24".

![2023-11-23_09-14](https://github.com/verdigado/odoo-customize/assets/3354500/37551aa5-87de-47ae-acfb-8db94573b885)

**Comment by albig** [comment]
Ich musste #67 leider mit #74 reverten. Normale Mitarbeiter*innen können sonst keine Attendance-Records mehr anlegen. 

Fehlermeldung:

![Clipboard - November 30, 2023 8_03](https://github.com/verdigado/odoo-customize/assets/3354500/c40d0770-bca2-473f-b631-53223255789b)

**Comment by hbrunn** [comment]
oh nein, da fehlt ein `sudo()` in https://github.com/verdigado/odoo-customize/pull/67/files#diff-14b295672daec20809ffd281a7f649c723c81c2bfe09d6f2ae4f4f105642c0b8R36 falls Du das selbst reparieren willst, ich bin gerade anderweitig eingespannt

**Comment by hbrunn** [comment]
Also es muss:

`self.env["hr.attendance.overtime"].sudo().create(missing_vals)`

sein. Wir sollten echt bald test cases fuer alle Rollen bauen, dann kann sowas nicht mehr passieren, weil die CI schon geschrien haette.

**Comment by albig** [comment]
Danke, das probier ich aus. Morgen. Heute muss ich leider zu anderen Dingen...

**Comment by albig** [comment]
Closed with #76
