### ISSUE TITLE
Bericht Abwesenheitsanalyse -> nach Abwesenheitsarten lässt sich nicht zum Dashboard hinzufügen.

### ISSUE THREAD

**Issue by albig** [verdigado/odoo-customize#68]
Die Ansicht unter Unter "Abwesenheiten -> Berichtswesen -> **nach Abwesenheitsarten**" lässt sich nicht zum Dashboard hinzufügen.

![2023-11-27_11-28](https://github.com/verdigado/odoo-customize/assets/3354500/67e60a0b-62f9-4e2d-8201-d7e4741d828a)

Die Ansicht "Abwesenheiten -> Berichtswesen -> nach Mitarbeitern" geht dagegen.

**Comment by hbrunn** [comment]
hier schnell reingeschaut da ich doch mit Dashboards zugange bin: Das geht nicht weil dieser Bericht keine window action ist, sondern eine [server action](https://github.com/OCA/OCB/blob/15.0/addons/hr_holidays/report/hr_leave_reports.xml#L72) die dann eine anonyme [window action](https://github.com/OCA/OCB/blob/15.0/addons/hr_holidays/report/hr_leave_report.py#L94) zurück gibt. Das ist nützlich um dieselbe Aktion sowohl auf employees als auch im Menu zu benutzen. Sollte relativ einfach sein das auseinander zu ziehen, und für das Menü eine eigene "echte" client action zu definieren.
