### ISSUE TITLE
Verknüpfung von Arbeitszeitmodell / Arbeitszeitvertrag mit den Urlaubsansprüchen

### ISSUE THREAD

**Issue by georgloesel** [verdigado/odoo-customize#75]
Anregung aus Bremen: 

wäre es möglich die Urlaubsansprüche fest an den Arbeitsvertrag bzw. das Arbeitszeitmodell zu knüpfen? 

wenn ein Standard 5 Tage / 38 Stunden / TVÖD Vertrag angelegt wird, wird analog dazu automatisch dem Mitarbeitenden ein 6 Wochen Urlaub zu geordnet. 

wenn der Arbeitsvertrag geändert wird, wird auch der Urlaubsanspruch geändert

**Comment by albig** [comment]
Idee: Lösung über einen Wizard. Alter ist nicht zu berücksichtigen. Wizard wird 1x jährlich durch Personalverantwortlichen ausgeführt und prüft.
