### ISSUE TITLE
Adjustments in Anwesenheits-Analyse 

### ISSUE THREAD

**Issue by albig** [verdigado/odoo-customize#78]
Im Anwesenheits-Bericht bzw. Anwesenheitsanalyse lässt sich der Gleitzeitkonto-Stand aller Mitarbeiter ansehen (passende Rechte vorausgesetzt). Das Saldo des "Gleitzeitkontostands" unterscheidet sich jedoch teilweise zu der Anzeige der Überstunden bei den Mitarbeitern.

Letzteres entspricht ja z.B. der Query `SELECT SUM("duration") FROM "hr_attendance_overtime" WHERE "employee_id" = '27'`.

Es fehlt vermutlich die Berücksichtigung der `adjustment=True`-Einträge im Bericht:

![2023-12-04_14-46](https://github.com/verdigado/odoo-customize/assets/3354500/cc54e328-402a-4b95-8792-46eafc71c961)

Folgende Abweichungen habe ich beim o.g. Beispiel:

| Gleitzeitkontostand | SUM("duration") | SUM("duration"), adjustment = True | 
|------------------------------| ------------------------|--- |
| 70:46 | 70:46 | 0 |
| **136:46** | 11:03 | -125:43 |
| **183:12** | 74:57 | -113:34 |
| **236:45** | 285:00 | -23:35 |
| **49:42** | 41:50 |-7:52 |
| 14:51 | 14:51 | 0 |
| 29:58 | 29:58 | 0 |
| -27:21 | -27:21 | 0 |
| **125:00** | 35:00 | -90 |
| **45:17** | 13:54 | 0 |

**Comment by hbrunn** [comment]
kannst Du mal in psql `\d+ hr_attendance_report` sagen ob es die UNION von https://github.com/verdigado/odoo-customize/blob/15.0/verdigado_attendance/models/hr_attendance_report.py#L19 anzeigt? Falls nicht: Hilft ein Update von verdigado_attendance?

Kann sein dass da ein Modul in die Suppe spuckt das nicht im dependency-tree von verdigado_attendance ist und den report verändert, in dem Fall muss eine entsprechende Dependency eingeführt werden.

Ansonsten schick mir am besten wieder einen anonymisierten DB-Dump.

**Comment by albig** [comment]
Sieht gut aus, oder? Ich pack Dir mal die anonymisierte DB zusammen.
```
                             View "public.hr_attendance_report"
     Column     |       Type       | Collation | Nullable | Default | Storage | Description 
----------------+------------------+-----------+----------+---------+---------+-------------
 id             | integer          |           |          |         | plain   | 
 department_id  | integer          |           |          |         | plain   | 
 employee_id    | integer          |           |          |         | plain   | 
 check_in       | date             |           |          |         | plain   | 
 worked_hours   | double precision |           |          |         | plain   | 
 overtime_hours | double precision |           |          |         | plain   | 
 break_hours    | double precision |           |          |         | plain   | 
 expected_hours | double precision |           |          |         | plain   | 
View definition:
 SELECT hra.id,
    hr_employee.department_id,
    hra.employee_id,
    hra.check_in,
    hra.worked_hours,
    COALESCE(ot.duration, 0::double precision) AS overtime_hours,
    hra.break_hours,
    COALESCE(ot.expected_hours, 0::double precision) AS expected_hours
   FROM ( SELECT hr_attendance.id,
            row_number() OVER (PARTITION BY hr_attendance.employee_id, (hr_attendance.check_in::date)) AS ot_check,
            hr_attendance.employee_id,
            timezone((( SELECT calendar.tz
                   FROM resource_calendar calendar
                     JOIN hr_employee employee ON employee.id = hr_attendance.employee_id
                  WHERE calendar.id = employee.resource_calendar_id))::text, timezone('utc'::text, hr_attendance.check_in))::date AS check_in,
            hr_attendance.worked_hours,
            hr_attendance.break_hours
           FROM hr_attendance) hra
     LEFT JOIN hr_employee ON hr_employee.id = hra.employee_id
     LEFT JOIN hr_attendance_overtime ot ON hra.ot_check = 1 AND ot.employee_id = hra.employee_id AND ot.date = hra.check_in AND ot.adjustment = false
UNION
 SELECT hra.id,
    hr_employee.department_id,
    hra.employee_id,
    hra.check_in,
    0 AS worked_hours,
    COALESCE(0, 0) AS overtime_hours,
    0 AS break_hours,
    0 AS expected_hours
   FROM ( SELECT hr_attendance.id,
            row_number() OVER (PARTITION BY hr_attendance.employee_id, (hr_attendance.check_in::date)) AS ot_check,
            hr_attendance.employee_id,
            timezone((( SELECT calendar.tz
                   FROM resource_calendar calendar
                     JOIN hr_employee employee ON employee.id = hr_attendance.employee_id
                  WHERE calendar.id = employee.resource_calendar_id))::text, timezone('utc'::text, hr_attendance.check_in))::date AS check_in,
            hr_attendance.worked_hours,
            hr_attendance.break_hours
           FROM hr_attendance) hra
     LEFT JOIN hr_employee ON hr_employee.id = hra.employee_id
     LEFT JOIN hr_attendance_overtime ot ON hra.ot_check = 1 AND ot.employee_id = hra.employee_id AND ot.date = hra.check_in AND ot.adjustment = true;


```

**Comment by hbrunn** [comment]
...haben wir hier ein Problem mit der Tatsache, dass Du im Report ein Zeitintervall angibst, die Adjustments aber uber immer aufsummiert werden mussen? Scheint mir gerade naheliegend dass ich in alle Selektionen des Reports ein `or adjustment=True` reinmanipulieren muss?
