### ISSUE TITLE
Dashboard um Login erweitern und als Startseite bzw. zentrale InfoPoint festlegen

### ISSUE THREAD

**Issue by georgloesel** [verdigado/odoo-customize#82]
Ist es möglich, das Dashboard als Startseite zu definieren und den An/Abmeldedialog dort mit zu integrieren. 
Damit hätten die Nutzenden einen zentralen Punkt, "the Place to be" 

![2023-12-13_21-48](https://github.com/verdigado/odoo-customize/assets/14213446/34a9d8cc-289c-422f-b5ee-d89b58b686be)

in einer späteren Ausbaustufe, könnte man von dort aus dann noch direkt die Seiten für Urlaub beantragen einbinden

**Comment by albig** [comment]
Dashboard als Startseite ist kein Problem.

Wizard auf dem Dashboard prüft @hbrunn

**Comment by hbrunn** [comment]
dass die Startseite mit aktiviertem Debug-Modus im Benutzerformular (nicht Profil) angepasst werden kann ist bekannt?

![image](https://github.com/verdigado/odoo-customize/assets/2563186/2e641f15-1918-4753-8b5c-c57c8a29c90e)

ihr braucht da die Aktion 'My dashboard'
