### ISSUE TITLE
Anlegen von neuen Benutzer:innen nur im Entwicklermodus 

### ISSUE THREAD

**Issue by georgloesel** [verdigado/odoo-customize#90]
Nur im Entwicklermodus können beim Anlegen von Benutzer:innen alle Optionen gewählt werden. 

ansonsten gibt es folgende Fehlermeldung:

![image](https://github.com/verdigado/odoo-customize/assets/14213446/3488e692-b808-4f6f-867f-3732ef40304b)

**Comment by albig** [comment]
closed by #94
