### ISSUE TITLE
Anzeige des Gleitzeitkonto-Stands ist 0:00 nach Update auf Odoo 15.0 20240104

### ISSUE THREAD

**Issue by albig** [verdigado/odoo-customize#92]
Nach dem Update auf Odoo 15.0 20240104 wird der Stand des Gleitzeitkontos ("Überstunden") bei allen Mitarbeitern mit "0:00" angezeigt.

![2024-01-08_10-14](https://github.com/verdigado/odoo-customize/assets/3354500/1c46ce7b-d6d9-42a4-bfe1-73ac3a67fdfa)

Geht man aber in den Mitarbeiter-Record, wird der korrekte Wert angezeigt. Die Tabelle `hr_attendance_overtime` ist gefüllt und der Select `SELECT SUM("duration") FROM "hr_attendance_overtime" WHERE "employee_id" = '18'` liefert im Beispiel `22.835833333333287`.

![2024-01-08_10-14_1](https://github.com/verdigado/odoo-customize/assets/3354500/5f59c27c-891d-487e-86fc-267560b57263)

Möglicherweise related zu #91

**Comment by hbrunn** [comment]
ja, habe den fix hierfür dann auch in den fix fur #91 gesteckt

**Comment by albig** [comment]
Danke Dir. Mich hat das auch erstaunt, dass man sowas im "alten" stable Branch macht.

In der oberen Leiste stimmt es noch nicht oder ist bei mir was faul?

![2024-01-08_13-39](https://github.com/verdigado/odoo-customize/assets/3354500/ff0004de-8d73-4434-9c3b-67a807844de8)

**Comment by hbrunn** [comment]
das soeben auch repariert. Bin noch auf der Suche weshalb die Tests fehlschlagen in dem PR

**Comment by albig** [comment]
Ja, das passt jetzt. Prima.

ich warte mal noch, ob Du die Probleme mit den Tests findest und dann merge ich das.

![2024-01-08_13-58](https://github.com/verdigado/odoo-customize/assets/3354500/c433fca0-0b49-496e-92fb-b1d5b0ddb080)

**Comment by hbrunn** [comment]
tests sind jetzt auch gefixed, das hatte nichts hiermit zu tun sondern mit der Zeitabhängigkeit der Felder
