### ISSUE TITLE
Pausenabzug erfolgt nicht, wenn Soll-Arbeitszeit == Ist (Anwesenheit)

### ISSUE THREAD

**Issue by albig** [verdigado/odoo-customize#96]
Beispiel:

Mitarbeiter hat 

- Soll-Arbeitszeit von 07:00 Stunden.
- als Anwesenheiten werden genau 07:00 Stunden gebucht
- zusätzlich wird eine Pause von 0:30 gebucht

Jetzt müsste als Überstunden "- 0:30" berechnet werden. Es wird aber "0:00" berechnet. Es ist dabei egal, wie lange die Pause ist. Sie wird ignoriert.

Der Fall ist anders, als in https://github.com/verdigado/odoo-customize/issues/65

![2024-01-15_11-08](https://github.com/verdigado/odoo-customize/assets/3354500/5b2eb353-62e9-4900-9098-9fe514030310)

**Comment by hbrunn** [comment]
hast Du das auch mit dem Codestand von #81 getestet? Damit sollte das eigentlich nicht passieren

**Comment by albig** [comment]
Nein, noch nicht. Das wäre ja prima.

**Comment by albig** [comment]
Stimmt leider auch mit #81 nicht.

**Comment by hbrunn** [comment]
das ist jetzt im PR fur hr_attendance_break repariert

**Comment by albig** [comment]
Funktioniert. Danke!
